"use client";

import {
  ArrowLeft,
  Check,
  FileImage,
  GitMerge,
  Layers3,
  PackageSearch,
  Sparkles,
  Upload,
  X,
} from "lucide-react";
import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import { PatentThreeDViewer } from "@/components/patent/PatentThreeDViewer";
import type { PatentThreeDViewerItem } from "@/components/patent/PatentThreeDViewer";
import { Button } from "@/components/ui/Button";
import { Panel } from "@/components/ui/Panel";
import type {
  PatentAssetKind,
  PatentAssemblyNode,
  PatentComponentRecord,
  PatentImageVariant,
  PatentReviewAction,
  PatentWorkspaceManifest,
} from "@/lib/patent-workspace";

type WorkspaceResponse = {
  workspace: PatentWorkspaceManifest;
};

function kindLabel(kind: PatentAssetKind): string {
  if (kind === "full_product") {
    return "Full Product";
  }
  if (kind === "subassembly") {
    return "Subassembly";
  }
  return "Component";
}

function getImageVariantState(component: PatentComponentRecord, variant: PatentImageVariant = "realistic_display") {
  const legacyComponent = component as PatentComponentRecord & {
    generationStatus?: "idle" | "queued" | "running" | "succeeded" | "failed";
    generationError?: string | null;
    generatedAsset?: {
      outputPath: string;
      outputFilename: string;
      model: string;
      generatedAt: string;
    } | null;
  };

  return (
    component.imageVariants?.[variant] ??
    (variant === "realistic_display"
      ? {
          status: legacyComponent.generationStatus ?? "idle",
          error: legacyComponent.generationError ?? null,
          asset: legacyComponent.generatedAsset
            ? {
                ...legacyComponent.generatedAsset,
                variant,
              }
            : null,
        }
      : {
          status: "idle",
          error: null,
          asset: null,
        })
  );
}

function getImageVariantAsset(component: PatentComponentRecord, variant: PatentImageVariant = "realistic_display") {
  return getImageVariantState(component, variant).asset;
}

function StepCard({
  step,
  title,
  detail,
}: {
  step: string;
  title: string;
  detail: string;
}) {
  return (
    <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-4">
      <div className="mb-2 text-[11px] uppercase tracking-[0.24em] text-cyan-300">{step}</div>
      <div className="text-base font-semibold text-white">{title}</div>
      <p className="mt-1 text-sm text-[var(--text-secondary)]">{detail}</p>
    </div>
  );
}

function StatusBadge({
  label,
  tone = "default",
}: {
  label: string;
  tone?: "default" | "success" | "warn" | "danger";
}) {
  const tones: Record<string, string> = {
    default: "border-white/10 bg-white/5 text-[var(--text-secondary)]",
    success: "border-emerald-400/30 bg-emerald-500/10 text-emerald-200",
    warn: "border-amber-400/30 bg-amber-500/10 text-amber-200",
    danger: "border-red-400/30 bg-red-500/10 text-red-200",
  };

  return (
    <span className={`rounded-full border px-2 py-0.5 text-[11px] ${tones[tone]}`}>
      {label}
    </span>
  );
}

function assemblyRoleLabel(assembly: PatentAssemblyNode): string {
  if (assembly.role === "product") {
    return "Root Product";
  }
  if (assembly.role === "auxiliary") {
    return "Auxiliary";
  }
  if (assembly.role === "tooling_process") {
    return "Mechanism / Process";
  }
  return "Core Assembly";
}

export default function PatentExtractPage() {
  const [file, setFile] = useState<File | null>(null);
  const [patentIdInput, setPatentIdInput] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isLoadingWorkspace, setIsLoadingWorkspace] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [workspace, setWorkspace] = useState<PatentWorkspaceManifest | null>(null);
  const [reviewLoadingById, setReviewLoadingById] = useState<Record<string, boolean>>({});
  const [generationLoadingById, setGenerationLoadingById] = useState<Record<string, boolean>>({});
  const [threeDLoadingById, setThreeDLoadingById] = useState<Record<string, boolean>>({});
  const [isGeneratingThreeDSet, setIsGeneratingThreeDSet] = useState(false);
  const [isExplodedView, setIsExplodedView] = useState(false);
  const [mergeTargets, setMergeTargets] = useState<Record<string, string>>({});
  const autoGeneratedHeroKeyRef = useRef<string | null>(null);

  useEffect(() => {
    if (workspace || typeof window === "undefined") {
      return;
    }

    const patentId = new URLSearchParams(window.location.search).get("patentId");
    if (!patentId) {
      return;
    }

    setIsLoadingWorkspace(true);
    setError(null);

    fetch(`/patents/${patentId}/manifest.json?ts=${Date.now()}`, {
      cache: "no-store",
    })
      .then(async (response) => {
        if (!response.ok) {
          throw new Error("Unable to load the saved patent workspace.");
        }
        const payload = (await response.json()) as PatentWorkspaceManifest;
        setWorkspace(payload);
      })
      .catch((loadError) => {
        setError(loadError instanceof Error ? loadError.message : "Unknown workspace loading error");
      })
      .finally(() => {
        setIsLoadingWorkspace(false);
      });
  }, [workspace]);

  const pendingComponents = useMemo(
    () => workspace?.componentLibrary.filter((component) => component.reviewStatus === "pending") ?? [],
    [workspace],
  );

  const approvedComponents = useMemo(
    () => workspace?.componentLibrary.filter((component) => component.reviewStatus === "approved") ?? [],
    [workspace],
  );

  const heroComponent = useMemo(
    () =>
      workspace?.featured.heroComponentId
        ? approvedComponents.find((component) => component.id === workspace.featured.heroComponentId) ?? null
        : null,
    [approvedComponents, workspace],
  );

  const featuredSubassemblies = useMemo(() => {
    if (!workspace) {
      return [];
    }

    const assemblyIds = new Set(workspace.featured?.subassemblyAssemblyIds ?? []);
    return workspace.assemblies
      .filter((assembly) => assemblyIds.has(assembly.id))
      .map((assembly) => ({
        assembly,
        representative:
          assembly.representativeComponentId != null
            ? workspace.componentLibrary.find((component) => component.id === assembly.representativeComponentId) ?? null
            : null,
        components: assembly.childComponentIds
          .map((componentId) => workspace.componentLibrary.find((component) => component.id === componentId) ?? null)
          .filter((component): component is PatentComponentRecord => Boolean(component)),
      }))
      .filter((item) => item.representative);
  }, [workspace]);

  const remainingApprovedComponents = useMemo(() => {
    const subassemblyIds = new Set(workspace?.featured.subassemblyComponentIds ?? []);
    return approvedComponents.filter(
      (component) => component.id !== heroComponent?.id && !subassemblyIds.has(component.id),
    );
  }, [approvedComponents, heroComponent, workspace]);

  const secondaryComponents = useMemo(
    () =>
      workspace?.componentLibrary.filter(
        (component) => component.reviewStatus === "redundant" || component.reviewStatus === "skipped",
      ) ?? [],
    [workspace],
  );

  const sortedFigures = useMemo(
    () => [...(workspace?.figures ?? [])].sort((a, b) => a.pageNumber - b.pageNumber),
    [workspace],
  );

  const featuredThreeDComponents = useMemo(() => {
    if (!workspace || !heroComponent) {
      return [];
    }

    const items = [heroComponent];
    for (const subassembly of featuredSubassemblies) {
      if (subassembly.representative) {
        items.push(subassembly.representative);
      }
    }

    return Array.from(new Map(items.map((component) => [component.id, component])).values());
  }, [featuredSubassemblies, heroComponent, workspace]);

  const allAssembledComponents = useMemo(() => {
    if (!workspace) return [];
    return workspace.componentLibrary.filter(
      (c) =>
        c.assemblyContract &&
        c.buildableStatus !== "feature_only",
    );
  }, [workspace]);

  const patentThreeDViewerItems = useMemo((): PatentThreeDViewerItem[] =>
    allAssembledComponents.map((c) => ({
      id: c.id,
      name: c.canonicalName,
      refNumber: c.canonicalRefNumber ?? undefined,
      kind: c.kind,
      description: c.evidence[0]?.summary,
      url: c.threeDAsset?.outputPath ?? null,
      contract: c.assemblyContract!,
    })),
  [allAssembledComponents]);

  const threeDWarnings = useMemo(
    () =>
      featuredThreeDComponents.flatMap((component) =>
        (component.assemblyContract?.fitWarnings ?? []).map((warning) => ({
          componentId: component.id,
          componentName: component.canonicalName,
          warning,
        })),
      ),
    [featuredThreeDComponents],
  );

  const hasActiveJobs = useMemo(() => {
    if (!workspace) {
      return false;
    }

    return workspace.componentLibrary.some((component) => {
      const displayState = getImageVariantState(component, "realistic_display").status;
      const sourceState = getImageVariantState(component, "three_d_source").status;
      return (
        displayState === "queued" ||
        displayState === "running" ||
        sourceState === "queued" ||
        sourceState === "running" ||
        component.threeDStatus === "queued" ||
        component.threeDStatus === "running"
      );
    });
  }, [workspace]);

  const threeDProgress = useMemo(() => {
    const queued = featuredThreeDComponents.filter((component) => component.threeDStatus === "queued");
    const running = featuredThreeDComponents.filter((component) => component.threeDStatus === "running");
    const completed = featuredThreeDComponents.filter((component) => component.threeDStatus === "succeeded");
    const sourceRunning = featuredThreeDComponents.filter(
      (component) => getImageVariantState(component, "three_d_source").status === "running",
    );
    const sourceQueued = featuredThreeDComponents.filter(
      (component) => getImageVariantState(component, "three_d_source").status === "queued",
    );

    return {
      queued,
      running,
      completed,
      sourceRunning,
      sourceQueued,
    };
  }, [featuredThreeDComponents]);

  useEffect(() => {
    if (!workspace || !heroComponent || !workspace.capabilities?.imageGeneration) {
      return;
    }

    const autoKey = `${workspace.patentId}:${heroComponent.id}`;
    if (autoGeneratedHeroKeyRef.current === autoKey) {
      return;
    }

    const heroDisplayState = getImageVariantState(heroComponent, "realistic_display");
    if (heroDisplayState.asset || heroDisplayState.status !== "idle") {
      return;
    }

    autoGeneratedHeroKeyRef.current = autoKey;
    void handleGenerateComponent(heroComponent.id, "realistic_display");
  }, [heroComponent, workspace]);

  // Auto-trigger 3D set generation once featured images are ready
  const autoThreeDKeyRef = useRef<string | null>(null);
  useEffect(() => {
    if (!workspace || !workspace.capabilities?.threeDGeneration || isGeneratingThreeDSet) {
      return;
    }

    const autoKey = `${workspace.patentId}:3d`;
    if (autoThreeDKeyRef.current === autoKey) {
      return;
    }

    // Check: at least the hero has a display image, and no 3D has been generated yet
    const hasAnyThreeD = featuredThreeDComponents.some(
      (c) => c.threeDStatus === "succeeded" || c.threeDStatus === "queued" || c.threeDStatus === "running",
    );
    if (hasAnyThreeD) {
      return;
    }

    // Check: hero has at least a display image ready
    const heroHasImage = heroComponent && getImageVariantState(heroComponent, "realistic_display").asset;
    if (!heroHasImage) {
      return;
    }

    autoThreeDKeyRef.current = autoKey;
    void handleGenerateThreeDSet(false);
  }, [workspace, heroComponent, featuredThreeDComponents, isGeneratingThreeDSet]);

  async function loadWorkspaceManifest(patentId: string, options?: { silent?: boolean }) {
    const silent = options?.silent ?? false;
    if (!silent) {
      setIsLoadingWorkspace(true);
    }

    try {
      const response = await fetch(`/api/patent/workspace?patentId=${encodeURIComponent(patentId)}&ts=${Date.now()}`, {
        cache: "no-store",
      });
      if (!response.ok) {
        throw new Error("Unable to load the saved patent workspace.");
      }
      const payload = (await response.json()) as PatentWorkspaceManifest;
      setWorkspace(payload);
    } catch (loadError) {
      if (!silent) {
        setError(loadError instanceof Error ? loadError.message : "Unknown workspace loading error");
      }
    } finally {
      if (!silent) {
        setIsLoadingWorkspace(false);
      }
    }
  }

  useEffect(() => {
    if (workspace || typeof window === "undefined") {
      return;
    }

    const patentId = new URLSearchParams(window.location.search).get("patentId");
    if (!patentId) {
      return;
    }

    setError(null);
    void loadWorkspaceManifest(patentId);
  }, [workspace]);

  useEffect(() => {
    if (!workspace || !hasActiveJobs) {
      return;
    }

    const intervalId = window.setInterval(() => {
      void loadWorkspaceManifest(workspace.patentId, { silent: true });
    }, 2200);

    return () => {
      window.clearInterval(intervalId);
    };
  }, [hasActiveJobs, workspace]);

  function syncWorkspace(payload: PatentWorkspaceManifest) {
    setWorkspace(payload);
    if (typeof window !== "undefined") {
      const url = new URL(window.location.href);
      url.searchParams.set("patentId", payload.patentId);
      window.history.replaceState({}, "", url.toString());
    }
  }

  async function handleSubmit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (!file) {
      setError("Please choose a PDF file first.");
      return;
    }

    setIsSubmitting(true);
    setError(null);

    try {
      const formData = new FormData();
      formData.append("file", file);
      if (patentIdInput.trim()) {
        formData.append("patentId", patentIdInput.trim());
      }

      const response = await fetch("/api/patent/extract", {
        method: "POST",
        body: formData,
      });

      const payload = (await response.json()) as PatentWorkspaceManifest | { error?: string };
      if (!response.ok) {
        throw new Error("error" in payload && payload.error ? payload.error : "Patent extraction failed.");
      }

      syncWorkspace(payload as PatentWorkspaceManifest);
      setMergeTargets({});
    } catch (submitError) {
      setWorkspace(null);
      setError(submitError instanceof Error ? submitError.message : "Unknown extraction error");
    } finally {
      setIsSubmitting(false);
    }
  }

  async function handleReviewAction(action: PatentReviewAction) {
    if (!workspace) {
      return;
    }

    setReviewLoadingById((current) => ({ ...current, [action.componentId]: true }));
    setError(null);

    try {
      const response = await fetch("/api/patent/components/review", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          patentId: workspace.patentId,
          action,
        }),
      });

      const payload = (await response.json()) as WorkspaceResponse | { error?: string };
      if (!response.ok) {
        throw new Error("error" in payload && payload.error ? payload.error : "Patent review action failed.");
      }

      syncWorkspace((payload as WorkspaceResponse).workspace);
    } catch (reviewError) {
      setError(reviewError instanceof Error ? reviewError.message : "Unknown review action error");
    } finally {
      setReviewLoadingById((current) => ({ ...current, [action.componentId]: false }));
    }
  }

  async function handleGenerateComponent(componentId: string, variant: PatentImageVariant = "realistic_display") {
    if (!workspace) {
      return;
    }

    const component = workspace.componentLibrary.find((item) => item.id === componentId);
    const forceRegenerate = Boolean(component && getImageVariantAsset(component, variant));

    setGenerationLoadingById((current) => ({ ...current, [componentId]: true }));
    setError(null);

    try {
      const response = await fetch("/api/patent/components/generate", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          patentId: workspace.patentId,
          componentId,
          variant,
          forceRegenerate,
        }),
      });

      const payload = (await response.json()) as WorkspaceResponse | { error?: string };
      if (!response.ok) {
        throw new Error("error" in payload && payload.error ? payload.error : "Component generation failed.");
      }

      syncWorkspace((payload as WorkspaceResponse).workspace);
    } catch (generationError) {
      setError(generationError instanceof Error ? generationError.message : "Unknown component generation error");
    } finally {
      setGenerationLoadingById((current) => ({ ...current, [componentId]: false }));
    }
  }

  async function handleGenerateThreeDSet(forceRegenerate = false) {
    if (!workspace) {
      return;
    }

    setIsGeneratingThreeDSet(true);
    setError(null);

    try {
      const response = await fetch("/api/patent/three-d/generate", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          patentId: workspace.patentId,
          mode: "featured-set",
          forceRegenerate,
        }),
      });

      const payload = (await response.json()) as WorkspaceResponse | { error?: string };
      if (!response.ok) {
        throw new Error("error" in payload && payload.error ? payload.error : "3D set generation failed.");
      }

      syncWorkspace((payload as WorkspaceResponse).workspace);
    } catch (generationError) {
      setError(generationError instanceof Error ? generationError.message : "Unknown 3D generation error");
    } finally {
      setIsGeneratingThreeDSet(false);
    }
  }

  async function handleGenerateThreeDComponent(componentId: string, forceRegenerate = true) {
    if (!workspace) {
      return;
    }

    setThreeDLoadingById((current) => ({ ...current, [componentId]: true }));
    setError(null);

    try {
      const response = await fetch("/api/patent/three-d/generate", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          patentId: workspace.patentId,
          mode: "component",
          componentId,
          forceRegenerate,
        }),
      });

      const payload = (await response.json()) as WorkspaceResponse | { error?: string };
      if (!response.ok) {
        throw new Error("error" in payload && payload.error ? payload.error : "3D component generation failed.");
      }

      syncWorkspace((payload as WorkspaceResponse).workspace);
    } catch (generationError) {
      setError(generationError instanceof Error ? generationError.message : "Unknown 3D component generation error");
    } finally {
      setThreeDLoadingById((current) => ({ ...current, [componentId]: false }));
    }
  }

  return (
    <main className="mx-auto min-h-screen w-full max-w-7xl px-4 py-8 md:px-6">
      <div className="mb-6 flex items-center justify-between gap-3">
        <Link
          href="/"
          className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-sm text-[var(--text-secondary)] transition-colors hover:text-white"
        >
          <ArrowLeft className="size-4" />
          Back to Globe
        </Link>
        <h1 className="text-xl font-semibold md:text-2xl">Patent Figure Extractor (POC)</h1>
      </div>

      <Panel className="mb-6 overflow-hidden">
        <div className="grid gap-6 p-4 md:grid-cols-[1.15fr_0.85fr] md:p-6">
          <div>
            <p className="max-w-2xl text-sm leading-6 text-[var(--text-secondary)]">
              Turn a patent PDF into a reviewed component asset library: extract source figures, normalize repeated
              parts into canonical components, preserve functional patent context, and generate isolated realistic
              renders for the approved pieces you want to keep.
            </p>

            <form onSubmit={handleSubmit} className="mt-5 grid gap-4 md:grid-cols-[1fr_1fr_auto] md:items-end">
              <label className="block text-sm">
                <span className="mb-1 block text-[var(--text-secondary)]">Patent PDF</span>
                <input
                  type="file"
                  accept="application/pdf"
                  onChange={(event) => setFile(event.target.files?.[0] ?? null)}
                  className="block w-full rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-sm"
                />
              </label>

              <label className="block text-sm">
                <span className="mb-1 block text-[var(--text-secondary)]">Patent ID (optional)</span>
                <input
                  type="text"
                  value={patentIdInput}
                  onChange={(event) => setPatentIdInput(event.target.value)}
                  placeholder="e.g. us-ballpoint-pen"
                  className="block w-full rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-sm"
                />
              </label>

              <Button type="submit" size="lg" loading={isSubmitting} className="md:w-56" disabled={!file}>
                <Upload className="size-4" />
                Extract Components
              </Button>
            </form>

            <div className="mt-3 text-xs text-[var(--text-secondary)]">
              Patent workspaces are cached in Vercel Blob when configured, with local workspace storage as the
              development fallback.
            </div>

            {error ? (
              <div className="mt-4 rounded-xl border border-red-400/40 bg-red-500/10 p-3 text-sm text-red-200">
                {error}
              </div>
            ) : null}
          </div>

          <div className="grid gap-3 md:grid-cols-1">
            <StepCard
              step="Step 1"
              title="Extract Source Evidence"
              detail="Detect figure crops and raw candidate parts from the patent pages."
            />
            <StepCard
              step="Step 2"
              title="AI Self-Review"
              detail="Auto-approve hero and likely subassemblies, and only surface ambiguous leftovers."
            />
            <StepCard
              step="Step 3"
              title="Hero + Subassemblies"
              detail="Generate one assembled hero image first, then work through approved subassemblies."
            />
          </div>
        </div>
      </Panel>

      {isLoadingWorkspace ? (
        <Panel className="mb-6 p-4 text-sm text-[var(--text-secondary)]">Loading saved patent workspace...</Panel>
      ) : null}

      {workspace ? (
        <>
          <Panel className="mb-6 p-4 md:p-6">
            <div className="grid gap-3 md:grid-cols-5">
              <div>
                <div className="text-xs uppercase tracking-wide text-[var(--text-secondary)]">Patent ID</div>
                <div className="mt-1 font-medium text-white">{workspace.patentId}</div>
              </div>
              <div>
                <div className="text-xs uppercase tracking-wide text-[var(--text-secondary)]">Pages</div>
                <div className="mt-1 font-medium text-white">
                  {workspace.processedPages} / {workspace.totalPages}
                </div>
              </div>
              <div>
                <div className="text-xs uppercase tracking-wide text-[var(--text-secondary)]">Source Figures</div>
                <div className="mt-1 font-medium text-white">{workspace.stats.figureCount}</div>
              </div>
              <div>
                <div className="text-xs uppercase tracking-wide text-[var(--text-secondary)]">Raw Candidates</div>
                <div className="mt-1 font-medium text-white">{workspace.stats.rawCandidateCount}</div>
              </div>
              <div>
                <div className="text-xs uppercase tracking-wide text-[var(--text-secondary)]">Canonical Components</div>
                <div className="mt-1 font-medium text-white">{workspace.stats.libraryCount}</div>
              </div>
            </div>

            <div className="mt-5 grid gap-3 md:grid-cols-4">
              <div className="rounded-xl border border-cyan-400/20 bg-cyan-500/10 p-3">
                <div className="text-xs uppercase tracking-wide text-cyan-100/80">Needs Review</div>
                <div className="mt-1 text-2xl font-semibold text-white">{workspace.stats.pendingCount}</div>
              </div>
              <div className="rounded-xl border border-emerald-400/20 bg-emerald-500/10 p-3">
                <div className="text-xs uppercase tracking-wide text-emerald-100/80">Approved</div>
                <div className="mt-1 text-2xl font-semibold text-white">{workspace.stats.approvedCount}</div>
              </div>
              <div className="rounded-xl border border-white/10 bg-white/[0.04] p-3">
                <div className="text-xs uppercase tracking-wide text-[var(--text-secondary)]">Generated</div>
                <div className="mt-1 text-2xl font-semibold text-white">{workspace.stats.generatedCount}</div>
              </div>
              <div className="rounded-xl border border-amber-400/20 bg-amber-500/10 p-3">
                <div className="text-xs uppercase tracking-wide text-amber-100/80">Subassemblies</div>
                <div className="mt-1 text-2xl font-semibold text-white">
                  {(workspace.featured?.subassemblyAssemblyIds ?? []).length}
                </div>
              </div>
            </div>

            <div className="mt-5 rounded-2xl border border-cyan-400/20 bg-cyan-500/10 p-4">
              <div className="flex flex-wrap items-center gap-2">
                <div className="text-xs uppercase tracking-[0.24em] text-cyan-200/80">Root Product</div>
                <StatusBadge label={workspace.productModel?.rootProductName ?? heroComponent?.canonicalName ?? "Patent product"} tone="success" />
              </div>
              <p className="mt-2 text-sm text-white">
                {workspace.productModel?.rootProductDescription ?? heroComponent?.summary ?? "Patent-derived product context will appear here after extraction planning."}
              </p>
              <div className="mt-3 flex flex-wrap gap-2 text-xs">
                {(workspace.productModel?.candidateAssemblyNames ?? []).map((assemblyName) => (
                  <StatusBadge key={assemblyName} label={assemblyName} />
                ))}
              </div>
            </div>

            <div className="mt-4 flex flex-wrap items-center gap-2 text-xs text-[var(--text-secondary)]">
              <a href={workspace.paths.manifestPath} target="_blank" rel="noreferrer" className="text-cyan-300 hover:text-cyan-200">
                Open manifest JSON
              </a>
              <span className="text-white/20">•</span>
              <a href={workspace.paths.textPath} target="_blank" rel="noreferrer" className="text-cyan-300 hover:text-cyan-200">
                Open extracted text
              </a>
            </div>

            {workspace.warnings.length > 0 ? (
              <div className="mt-4 rounded-xl border border-amber-400/40 bg-amber-500/10 p-3 text-sm text-amber-100">
                <p className="mb-1 font-medium">Warnings</p>
                <ul className="list-disc space-y-1 pl-5">
                  {workspace.warnings.map((warning) => (
                    <li key={warning}>{warning}</li>
                  ))}
                </ul>
              </div>
            ) : null}
          </Panel>

          <Panel className="mb-6 p-4 md:p-6">
            <div className="mb-4 flex items-center gap-3">
              <Sparkles className="size-5 text-cyan-300" />
              <div>
                <h2 className="text-lg font-semibold text-white">Hero Output</h2>
                <p className="text-sm text-[var(--text-secondary)]">
                  One assembled product-style image to represent the overall object before exploding subassemblies.
                </p>
              </div>
            </div>

            {heroComponent ? (
              <div className="grid gap-4 lg:grid-cols-[1.1fr_0.9fr]">
                <div className="space-y-3 rounded-2xl border border-white/10 bg-white/[0.03] p-4">
                  <div className="flex flex-wrap items-center gap-2">
                    <h3 className="text-lg font-semibold text-white">{heroComponent.canonicalName}</h3>
                    <StatusBadge label={kindLabel(heroComponent.kind)} tone="success" />
                    <StatusBadge
                      label={heroComponent.role === "root_product" ? "Root Product" : heroComponent.role ?? kindLabel(heroComponent.kind)}
                      tone="success"
                    />
                    {heroComponent.canonicalRefNumber ? (
                      <StatusBadge label={`Ref ${heroComponent.canonicalRefNumber}`} tone="success" />
                    ) : null}
                    <StatusBadge label={`${Math.round(heroComponent.confidence * 100)}% confidence`} />
                    <StatusBadge label={(heroComponent.evidenceMode ?? "figure_context").replaceAll("_", " ")} />
                    <StatusBadge label={heroComponent.buildableStatus ?? "buildable"} />
                  </div>

                  <p className="text-sm text-[var(--text-secondary)]">{heroComponent.summary}</p>
                  <p className="text-xs text-cyan-300">{heroComponent.autoReviewReason}</p>

                  <div className="grid gap-3 md:grid-cols-2">
                    <div className="rounded-xl border border-white/10 bg-black/20 p-3">
                      <div className="mb-1 text-[11px] uppercase tracking-wide text-[var(--text-secondary)]">
                        How It Works
                      </div>
                      <p className="text-sm text-white">{heroComponent.functionDescription}</p>
                    </div>
                    <div className="rounded-xl border border-white/10 bg-black/20 p-3">
                      <div className="mb-1 text-[11px] uppercase tracking-wide text-[var(--text-secondary)]">
                        Scale Hint
                      </div>
                      <p className="text-sm text-white">
                        Approx. {(heroComponent.scaleHints?.relativeArea ?? 0) * 100 < 1
                          ? "<1"
                          : Math.round((heroComponent.scaleHints?.relativeArea ?? 0) * 100)}
                        % of page area across its evidence views.
                      </p>
                    </div>
                  </div>

                    <div className="rounded-xl border border-white/10 bg-black/20 p-3">
                      <div className="mb-1 text-[11px] uppercase tracking-wide text-[var(--text-secondary)]">
                        Product Context
                      </div>
                    <p className="text-sm text-white">
                      {heroComponent.supportingContext?.rootProductDescription ?? heroComponent.summary}
                    </p>
                  </div>

                  <div className="flex flex-wrap gap-2 text-xs">
                    <StatusBadge label={`${heroComponent.evidence.length} evidence view${heroComponent.evidence.length === 1 ? "" : "s"}`} />
                    {heroComponent.refNumbers.map((refNumber) => (
                      <StatusBadge key={`${heroComponent.id}-${refNumber}`} label={`Ref ${refNumber}`} tone="success" />
                    ))}
                  </div>

                  <div className="grid grid-cols-3 gap-2">
                    {heroComponent.evidence.slice(0, 3).map((evidence, index) => (
                      <img
                        key={`${evidence.candidateId}-${evidence.figureId}-${evidence.pageNumber}-${index}`}
                        src={evidence.imagePath}
                        alt={`${heroComponent.canonicalName} evidence ${evidence.figureLabel}`}
                        className="h-24 w-full rounded-xl border border-white/10 bg-black/30 object-contain"
                      />
                    ))}
                  </div>
                </div>

                <div className="rounded-2xl border border-white/10 bg-black/20 p-4">
                  {(() => {
                    const heroDisplayState = getImageVariantState(heroComponent, "realistic_display");
                    const heroDisplayAsset = heroDisplayState.asset;
                    const heroThreeDSourceState = getImageVariantState(heroComponent, "three_d_source");
                    return (
                      <>
                  <div className="mb-3 flex items-center justify-between gap-3">
                    <div>
                      <div className="text-base font-semibold text-white">Assembled Hero Image</div>
                      <div className="text-xs text-[var(--text-secondary)]">
                        Automatically generated once the workspace identifies a hero candidate.
                      </div>
                    </div>
                    <Button
                      type="button"
                      size="sm"
                      loading={generationLoadingById[heroComponent.id] ?? false}
                      onClick={() => handleGenerateComponent(heroComponent.id, "realistic_display")}
                      disabled={!workspace.capabilities?.imageGeneration}
                    >
                      <Sparkles className="size-4" />
                      {heroDisplayAsset ? "Re-run" : "Generate"}
                    </Button>
                  </div>

                  {heroDisplayAsset ? (
                    <a href={heroDisplayAsset.outputPath} target="_blank" rel="noreferrer" className="block">
                      <img
                        src={heroDisplayAsset.outputPath}
                        alt={`Hero render for ${heroComponent.canonicalName}`}
                        className="h-80 w-full rounded-xl border border-white/10 bg-black/30 object-contain"
                      />
                    </a>
                  ) : (
                    <div className="flex h-80 items-center justify-center rounded-xl border border-dashed border-white/10 bg-black/10 px-4 text-center text-sm text-[var(--text-secondary)]">
                      Preparing the assembled hero output.
                    </div>
                  )}

                  <div className="mt-2 flex items-center justify-between gap-2 text-[11px] text-[var(--text-secondary)]">
                    <span>{heroDisplayState.status}</span>
                    {heroDisplayAsset ? (
                      <a
                        href={heroDisplayAsset.outputPath}
                        target="_blank"
                        rel="noreferrer"
                        className="text-cyan-300 hover:text-cyan-200"
                      >
                        Open hero image
                      </a>
                    ) : null}
                  </div>

                  <div className="mt-3 rounded-xl border border-white/10 bg-white/[0.03] p-3 text-xs text-[var(--text-secondary)]">
                    3D source image:{" "}
                    <span className="text-white">
                      {heroThreeDSourceState.asset ? "ready" : heroThreeDSourceState.status}
                    </span>
                  </div>

                  {heroDisplayState.error ? (
                    <div className="mt-3 rounded-xl border border-red-400/40 bg-red-500/10 p-3 text-xs text-red-200">
                      {heroDisplayState.error}
                    </div>
                  ) : null}
                      </>
                    );
                  })()}
                </div>
              </div>
            ) : (
              <div className="rounded-xl border border-dashed border-white/10 bg-black/20 p-4 text-sm text-[var(--text-secondary)]">
                No reliable hero candidate was auto-identified from the extracted patent figures yet.
              </div>
            )}
          </Panel>

          <Panel className="mb-6 p-4 md:p-6">
            <div className="mb-4 flex items-center gap-3">
              <Layers3 className="size-5 text-cyan-300" />
              <div>
                <h2 className="text-lg font-semibold text-white">Auto-Identified Subassemblies</h2>
                <p className="text-sm text-[var(--text-secondary)]">
                  These are the grouped parts most useful for a hybrid assembled-plus-exploded workflow.
                </p>
              </div>
            </div>

            {featuredSubassemblies.length === 0 ? (
              <div className="rounded-xl border border-dashed border-white/10 bg-black/20 p-4 text-sm text-[var(--text-secondary)]">
                No grouped product assemblies were derived yet.
              </div>
            ) : (
              <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
                {featuredSubassemblies.map(({ assembly, representative, components }) => {
                  if (!representative) {
                    return null;
                  }
                  const displayAsset = getImageVariantAsset(representative, "realistic_display");
                  const displayState = getImageVariantState(representative, "realistic_display");
                  const sourceState = getImageVariantState(representative, "three_d_source");
                  const primaryEvidence = displayAsset ? null : representative.evidence[0];

                  return (
                    <div key={assembly.id} className="overflow-hidden rounded-2xl border border-white/10 bg-white/[0.03]">
                      <div className="border-b border-white/10 bg-black/20 p-3">
                        <div className="mb-2 flex items-center justify-between gap-2">
                          <div>
                            <div className="font-medium text-white">{assembly.name}</div>
                            <div className="text-xs text-[var(--text-secondary)]">{assemblyRoleLabel(assembly)}</div>
                          </div>
                          <Button
                            type="button"
                            size="sm"
                            loading={generationLoadingById[representative.id] ?? false}
                            onClick={() => handleGenerateComponent(representative.id, "realistic_display")}
                            disabled={!workspace.capabilities?.imageGeneration}
                          >
                            <Sparkles className="size-4" />
                            {displayAsset ? "Re-run" : "Generate"}
                          </Button>
                        </div>

                        {displayAsset ? (
                          <a href={displayAsset.outputPath} target="_blank" rel="noreferrer" className="block">
                            <img
                              src={displayAsset.outputPath}
                              alt={`Generated render for ${assembly.name}`}
                              className="h-56 w-full rounded-xl border border-white/10 bg-black/30 object-contain"
                            />
                          </a>
                        ) : primaryEvidence ? (
                          <img
                            src={primaryEvidence.imagePath}
                            alt={`Source evidence for ${assembly.name}`}
                            className="h-56 w-full rounded-xl border border-white/10 bg-black/30 object-contain"
                          />
                        ) : null}
                      </div>

                      <div className="space-y-3 p-3 text-sm">
                        <p className="text-white">{assembly.summary}</p>
                        <p className="text-[var(--text-secondary)]">
                          {representative.supportingContext?.evidencePolicyNote ?? representative.summary}
                        </p>
                        <div className="text-xs text-cyan-300">{representative.autoReviewReason}</div>
                        {representative.reviewStatus !== "approved" ? (
                          <div className="text-xs text-amber-200">
                            Still marked as an AI review exception, but this featured subassembly can still be generated.
                          </div>
                        ) : null}
                        <div className="text-xs text-[var(--text-secondary)]">
                          Display image: {displayState.status} · 3D source: {sourceState.asset ? "ready" : sourceState.status}
                        </div>
                        <div className="flex flex-wrap gap-2 text-xs">
                          <StatusBadge label={`${components.length} part${components.length === 1 ? "" : "s"}`} />
                          <StatusBadge label={(representative.evidenceMode ?? "figure_context").replaceAll("_", " ")} />
                          <StatusBadge label={representative.reviewStatus} tone={representative.reviewStatus === "approved" ? "success" : "warn"} />
                          {representative.canonicalRefNumber ? (
                            <StatusBadge label={`Ref ${representative.canonicalRefNumber}`} tone="success" />
                          ) : null}
                          <StatusBadge
                            label={`Rep ${representative.canonicalName}`}
                          />
                        </div>
                      </div>
                    </div>
                  );
                })}
              </div>
            )}
          </Panel>

          <Panel className="mb-6 p-4 md:p-6">
            <div className="mb-4 flex flex-wrap items-center justify-between gap-3">
              <div className="flex items-center gap-3">
                <Layers3 className="size-5 text-cyan-300" />
                <div>
                  <h2 className="text-lg font-semibold text-white">Patent 3D Set</h2>
                  <p className="text-sm text-[var(--text-secondary)]">
                    Generate Trellis 2 meshes from the hero and featured subassembly source images, then preview the assembled or exploded set.
                  </p>
                </div>
              </div>
              <div className="flex flex-wrap items-center gap-2">
                <Button
                  type="button"
                  variant="secondary"
                  size="sm"
                  onClick={() => setIsExplodedView((current) => !current)}
                  disabled={patentThreeDViewerItems.length === 0}
                >
                  <Layers3 className="size-4" />
                  {isExplodedView ? "Show Assembled" : "Show Exploded"}
                </Button>
                <Button
                  type="button"
                  size="sm"
                  loading={isGeneratingThreeDSet}
                  onClick={() => handleGenerateThreeDSet(false)}
                  disabled={!workspace.capabilities?.threeDGeneration || !heroComponent}
                >
                  <Sparkles className="size-4" />
                  Generate 3D Set
                </Button>
              </div>
            </div>

            {!workspace.capabilities?.threeDGeneration ? (
              <div className="rounded-xl border border-amber-400/30 bg-amber-500/10 p-4 text-sm text-amber-100">
                `FAL_KEY` is not configured, so Trellis 2 generation is currently unavailable.
              </div>
            ) : null}

            <div className="grid gap-4 xl:grid-cols-[1.2fr_0.8fr]">
              <div className="space-y-4">
                {threeDProgress.running.length > 0 || threeDProgress.queued.length > 0 || threeDProgress.sourceRunning.length > 0 || threeDProgress.sourceQueued.length > 0 ? (
                  <div className="rounded-xl border border-cyan-400/20 bg-cyan-500/10 p-4 text-sm text-cyan-100">
                    <div className="font-medium text-white">3D generation is in progress.</div>
                    <div className="mt-1">
                      {threeDProgress.sourceRunning.length > 0
                        ? `Preparing 3D source image: ${threeDProgress.sourceRunning.map((component) => component.canonicalName).join(", ")}. `
                        : ""}
                      {threeDProgress.running.length > 0
                        ? `Generating GLB: ${threeDProgress.running.map((component) => component.canonicalName).join(", ")}. `
                        : ""}
                      {threeDProgress.sourceQueued.length > 0 || threeDProgress.queued.length > 0
                        ? `Queued next: ${[...threeDProgress.sourceQueued, ...threeDProgress.queued]
                            .map((component) => component.canonicalName)
                            .join(", ")}.`
                        : ""}
                    </div>
                    <div className="mt-2 text-xs text-cyan-200/80">
                      Completed {threeDProgress.completed.length} of {featuredThreeDComponents.length} featured meshes.
                    </div>
                  </div>
                ) : null}

                {patentThreeDViewerItems.length > 0 ? (
                  <PatentThreeDViewer
                    items={patentThreeDViewerItems}
                    exploded={isExplodedView}
                    onExplodedChange={setIsExplodedView}
                  />
                ) : (
                  <div className="flex h-[420px] items-center justify-center rounded-2xl border border-dashed border-white/10 bg-black/20 px-4 text-center text-sm text-[var(--text-secondary)]">
                    Generate the featured 3D set to preview the assembled and exploded layout here.
                  </div>
                )}

                <div className="grid gap-3 md:grid-cols-3">
                  <div className="rounded-xl border border-white/10 bg-white/[0.03] p-3">
                    <div className="text-xs uppercase tracking-wide text-[var(--text-secondary)]">Featured Meshes</div>
                    <div className="mt-1 text-2xl font-semibold text-white">{featuredThreeDComponents.length}</div>
                  </div>
                  <div className="rounded-xl border border-white/10 bg-white/[0.03] p-3">
                    <div className="text-xs uppercase tracking-wide text-[var(--text-secondary)]">Generated GLBs</div>
                    <div className="mt-1 text-2xl font-semibold text-white">{patentThreeDViewerItems.length}</div>
                  </div>
                  <div className="rounded-xl border border-white/10 bg-white/[0.03] p-3">
                    <div className="text-xs uppercase tracking-wide text-[var(--text-secondary)]">Fit Warnings</div>
                    <div className="mt-1 text-2xl font-semibold text-white">{threeDWarnings.length}</div>
                  </div>
                </div>
              </div>

              <div className="space-y-3">
                {featuredThreeDComponents.map((component) => {
                  const displayAsset = getImageVariantAsset(component, "realistic_display");
                  const sourceAsset = getImageVariantAsset(component, "three_d_source");

                  return (
                    <div key={component.id} className="rounded-2xl border border-white/10 bg-white/[0.03] p-4">
                      <div className="flex items-start justify-between gap-3">
                        <div>
                          <div className="flex flex-wrap items-center gap-2">
                            <div className="font-medium text-white">{component.canonicalName}</div>
                            <StatusBadge
                              label={component.id === workspace.featured.heroComponentId ? "Hero" : "Subassembly"}
                              tone="success"
                            />
                            {component.assemblyContract ? (
                              <StatusBadge label={component.assemblyContract.fitStatus} tone={component.assemblyContract.fitStatus === "pass" ? "success" : "warn"} />
                            ) : null}
                          </div>
                          <div className="mt-2 text-xs text-[var(--text-secondary)]">
                            Display image: {displayAsset ? "ready" : getImageVariantState(component, "realistic_display").status}
                          </div>
                          <div className="mt-1 text-xs text-[var(--text-secondary)]">
                            3D source: {sourceAsset ? "ready" : getImageVariantState(component, "three_d_source").status}
                          </div>
                          <div className="mt-1 text-xs text-[var(--text-secondary)]">
                            GLB: {component.threeDAsset ? "ready" : component.threeDStatus}
                          </div>
                        </div>
                        <Button
                          type="button"
                          size="sm"
                          loading={threeDLoadingById[component.id] ?? false}
                          onClick={() => handleGenerateThreeDComponent(component.id, true)}
                          disabled={!workspace.capabilities?.threeDGeneration}
                        >
                          <Sparkles className="size-4" />
                          {component.threeDAsset ? "Re-run 3D" : "Generate 3D"}
                        </Button>
                      </div>

                      {component.threeDAsset ? (
                        <div className="mt-3 flex flex-wrap gap-2 text-xs">
                          <a
                            href={component.threeDAsset.outputPath}
                            target="_blank"
                            rel="noreferrer"
                            className="text-cyan-300 hover:text-cyan-200"
                          >
                            Open GLB
                          </a>
                          <span className="text-white/20">•</span>
                          <span className="text-[var(--text-secondary)]">{component.threeDAsset.model}</span>
                        </div>
                      ) : null}

                      {component.assemblyContract ? (
                        <div className="mt-3 grid gap-2 text-xs md:grid-cols-2">
                          <div className="rounded-xl border border-white/10 bg-black/20 p-3">
                            <div className="text-[var(--text-secondary)]">Normalized Longest Axis</div>
                            <div className="mt-1 text-white">
                              {component.assemblyContract.normalizedBounds.longestAxis.toFixed(3)}
                            </div>
                          </div>
                          <div className="rounded-xl border border-white/10 bg-black/20 p-3">
                            <div className="text-[var(--text-secondary)]">Expected Linear Scale</div>
                            <div className="mt-1 text-white">
                              {component.assemblyContract.expectedLinearScale.toFixed(3)}
                            </div>
                          </div>
                        </div>
                      ) : null}

                      {component.threeDError ? (
                        <div className="mt-3 rounded-xl border border-red-400/40 bg-red-500/10 p-3 text-xs text-red-200">
                          {component.threeDError}
                        </div>
                      ) : null}

                      {component.assemblyContract?.fitWarnings.length ? (
                        <div className="mt-3 rounded-xl border border-amber-400/30 bg-amber-500/10 p-3 text-xs text-amber-100">
                          {component.assemblyContract.fitWarnings.join(" ")}
                        </div>
                      ) : null}
                    </div>
                  );
                })}
              </div>
            </div>
          </Panel>

          <Panel className="mb-6 p-4 md:p-6">
            <div className="mb-4 flex items-center gap-3">
              <PackageSearch className="size-5 text-cyan-300" />
              <div>
                <h2 className="text-lg font-semibold text-white">AI Review Exceptions</h2>
                <p className="text-sm text-[var(--text-secondary)]">
                  Only ambiguous candidates are left here. Everything else was auto-approved, skipped, or grouped.
                </p>
              </div>
            </div>

            {pendingComponents.length === 0 ? (
              <div className="rounded-xl border border-emerald-400/30 bg-emerald-500/10 p-4 text-sm text-emerald-100">
                No manual review is required right now.
              </div>
            ) : (
              <div className="grid gap-4 lg:grid-cols-2">
                {pendingComponents.map((component) => {
                  const mergeTargetOptions = workspace.componentLibrary.filter(
                    (option) => option.id !== component.id && option.reviewStatus !== "redundant",
                  );
                  const primaryEvidence = component.evidence[0];

                  return (
                    <div key={component.id} className="rounded-2xl border border-white/10 bg-white/[0.03] p-4">
                      <div className="mb-4 flex items-start justify-between gap-3">
                        <div>
                          <div className="flex flex-wrap items-center gap-2">
                            <h3 className="text-base font-semibold text-white">{component.canonicalName}</h3>
                            <StatusBadge label={kindLabel(component.kind)} />
                            {component.canonicalRefNumber ? (
                              <StatusBadge label={`Ref ${component.canonicalRefNumber}`} tone="success" />
                            ) : null}
                            <StatusBadge label={component.buildableStatus ?? "buildable"} />
                            <StatusBadge label={`${Math.round(component.confidence * 100)}% confidence`} />
                          </div>
                          <p className="mt-2 text-sm text-[var(--text-secondary)]">{component.summary}</p>
                          <p className="mt-1 text-xs text-cyan-300">{component.autoReviewReason}</p>
                        </div>
                        {primaryEvidence ? (
                          <img
                            src={primaryEvidence.imagePath}
                            alt={component.canonicalName}
                            className="h-20 w-20 rounded-xl border border-white/10 bg-black/20 object-contain"
                          />
                        ) : null}
                      </div>

                      <div className="grid gap-3 text-sm md:grid-cols-2">
                        <div className="rounded-xl border border-white/10 bg-black/20 p-3">
                          <div className="mb-1 text-[11px] uppercase tracking-wide text-[var(--text-secondary)]">
                            What It Is
                          </div>
                          <p className="text-[13px] text-white">{component.summary}</p>
                        </div>
                        <div className="rounded-xl border border-white/10 bg-black/20 p-3">
                          <div className="mb-1 text-[11px] uppercase tracking-wide text-[var(--text-secondary)]">
                            How It Works
                          </div>
                          <p className="text-[13px] text-white">{component.functionDescription}</p>
                        </div>
                      </div>

                      <div className="mt-3 flex flex-wrap gap-2 text-xs">
                        {component.refNumbers.length > 0 ? (
                          component.refNumbers.map((refNumber) => (
                            <StatusBadge key={`${component.id}-${refNumber}`} label={`Ref ${refNumber}`} tone="success" />
                          ))
                        ) : (
                          <StatusBadge label="No patent ref number" />
                        )}
                        <StatusBadge label={`${component.evidence.length} evidence image${component.evidence.length === 1 ? "" : "s"}`} />
                        <StatusBadge
                          label={`Scale ${(component.scaleHints?.relativeArea ?? 0) * 100 < 1 ? "<1" : Math.round((component.scaleHints?.relativeArea ?? 0) * 100)}%`}
                        />
                      </div>

                      <div className="mt-3 flex flex-wrap gap-2 text-xs text-[var(--text-secondary)]">
                        {component.evidence.slice(0, 6).map((evidence, index) => (
                          <span
                            key={`${evidence.candidateId}-${evidence.figureId}-${evidence.pageNumber}-${index}`}
                            className="rounded-full border border-white/10 bg-white/5 px-2 py-0.5"
                          >
                            {evidence.figureLabel} · p{evidence.pageNumber}
                          </span>
                        ))}
                      </div>

                      <div className="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-4">
                        <Button
                          type="button"
                          size="sm"
                          loading={reviewLoadingById[component.id] ?? false}
                          onClick={() => handleReviewAction({ type: "approve", componentId: component.id })}
                        >
                          <Check className="size-4" />
                          Approve
                        </Button>
                        <Button
                          type="button"
                          variant="secondary"
                          size="sm"
                          loading={reviewLoadingById[component.id] ?? false}
                          onClick={() => handleReviewAction({ type: "mark_subassembly", componentId: component.id })}
                        >
                          <Layers3 className="size-4" />
                          Subassembly
                        </Button>
                        <Button
                          type="button"
                          variant="ghost"
                          size="sm"
                          loading={reviewLoadingById[component.id] ?? false}
                          onClick={() => handleReviewAction({ type: "skip", componentId: component.id })}
                        >
                          <X className="size-4" />
                          Skip
                        </Button>
                        <Button
                          type="button"
                          variant="ghost"
                          size="sm"
                          loading={reviewLoadingById[component.id] ?? false}
                          onClick={() => handleReviewAction({ type: "mark_redundant", componentId: component.id })}
                        >
                          <X className="size-4" />
                          Redundant
                        </Button>
                      </div>

                      <div className="mt-3 grid gap-2 md:grid-cols-[1fr_auto]">
                        <select
                          value={mergeTargets[component.id] ?? ""}
                          onChange={(event) =>
                            setMergeTargets((current) => ({
                              ...current,
                              [component.id]: event.target.value,
                            }))
                          }
                          className="h-11 rounded-xl border border-white/10 bg-white/5 px-3 text-sm text-white"
                        >
                          <option value="">Select canonical target to merge into</option>
                          {mergeTargetOptions.map((option) => (
                            <option key={option.id} value={option.id}>
                              {option.canonicalName}
                            </option>
                          ))}
                        </select>
                        <Button
                          type="button"
                          variant="secondary"
                          size="sm"
                          className="h-11"
                          disabled={!mergeTargets[component.id]}
                          loading={reviewLoadingById[component.id] ?? false}
                          onClick={() =>
                            handleReviewAction({
                              type: "merge",
                              componentId: component.id,
                              targetComponentId: mergeTargets[component.id],
                            })
                          }
                        >
                          <GitMerge className="size-4" />
                          Merge
                        </Button>
                      </div>
                    </div>
                  );
                })}
              </div>
            )}
          </Panel>

          <Panel className="mb-6 p-4 md:p-6">
            <div className="mb-4 flex items-center gap-3">
              <FileImage className="size-5 text-cyan-300" />
              <div>
                <h2 className="text-lg font-semibold text-white">Reference Index</h2>
                <p className="text-sm text-[var(--text-secondary)]">
                  Patent callout numbers merged across figures into canonical reference records for exploded-view planning.
                </p>
              </div>
            </div>

            {(workspace.referenceIndex ?? []).length === 0 ? (
              <div className="rounded-xl border border-dashed border-white/10 bg-black/20 p-4 text-sm text-[var(--text-secondary)]">
                No patent reference index was derived yet.
              </div>
            ) : (
              <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
                {(workspace.referenceIndex ?? []).slice(0, 18).map((reference) => (
                  <div key={reference.refNumber} className="rounded-2xl border border-white/10 bg-white/[0.03] p-4">
                    <div className="flex flex-wrap items-center gap-2">
                      <StatusBadge label={`Ref ${reference.refNumber}`} tone="success" />
                      <StatusBadge label={reference.buildableStatus} />
                    </div>
                    <div className="mt-2 font-medium text-white">{reference.canonicalLabel}</div>
                    <p className="mt-2 text-sm text-white">{reference.summary}</p>
                    <p className="mt-2 text-sm text-[var(--text-secondary)]">{reference.functionDescription}</p>
                    <div className="mt-3 flex flex-wrap gap-2 text-xs">
                      <StatusBadge
                        label={`${reference.supportingFigureLabels.length} figure${reference.supportingFigureLabels.length === 1 ? "" : "s"}`}
                      />
                      {reference.parentComponentId ? <StatusBadge label="Attached feature" tone="warn" /> : null}
                    </div>
                  </div>
                ))}
              </div>
            )}
          </Panel>

          <Panel className="mb-6 p-4 md:p-6">
            <div className="mb-4 flex items-center gap-3">
              <Sparkles className="size-5 text-cyan-300" />
              <div>
                <h2 className="text-lg font-semibold text-white">Other Approved Components</h2>
                <p className="text-sm text-[var(--text-secondary)]">
                  Additional approved components beyond the hero object and the main subassemblies.
                </p>
              </div>
            </div>

            {remainingApprovedComponents.length === 0 ? (
              <div className="rounded-xl border border-dashed border-white/10 bg-black/20 p-4 text-sm text-[var(--text-secondary)]">
                No extra approved components beyond the current hero and subassembly set.
              </div>
            ) : (
              <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
                {remainingApprovedComponents.map((component) => {
                  const displayAsset = getImageVariantAsset(component, "realistic_display");
                  const displayState = getImageVariantState(component, "realistic_display");
                  const primaryEvidence = component.evidence[0];

                  return (
                    <div key={component.id} className="overflow-hidden rounded-2xl border border-white/10 bg-white/[0.03]">
                      <div className="border-b border-white/10 bg-black/20 p-3">
                        <div className="mb-2 flex items-center justify-between gap-2">
                          <div>
                            <div className="font-medium text-white">{component.canonicalName}</div>
                            <div className="text-xs text-[var(--text-secondary)]">{kindLabel(component.kind)}</div>
                          </div>
                          <Button
                            type="button"
                            size="sm"
                            loading={generationLoadingById[component.id] ?? false}
                            onClick={() => handleGenerateComponent(component.id, "realistic_display")}
                            disabled={!workspace.capabilities?.imageGeneration}
                          >
                            <Sparkles className="size-4" />
                            {displayAsset ? "Re-run" : "Generate"}
                          </Button>
                        </div>

                        {displayAsset ? (
                          <a href={displayAsset.outputPath} target="_blank" rel="noreferrer" className="block">
                            <img
                              src={displayAsset.outputPath}
                              alt={`Generated render for ${component.canonicalName}`}
                              className="h-64 w-full rounded-xl border border-white/10 bg-black/30 object-contain"
                            />
                          </a>
                        ) : primaryEvidence ? (
                          <div className="grid gap-3 md:grid-cols-[1fr_120px]">
                            <div className="flex h-40 items-center justify-center rounded-xl border border-dashed border-white/10 bg-black/20 px-4 text-center text-xs text-[var(--text-secondary)]">
                              No realistic render yet. Generate after review to create the clean studio asset.
                            </div>
                            <img
                              src={primaryEvidence.imagePath}
                              alt={`Source evidence for ${component.canonicalName}`}
                              className="h-40 w-full rounded-xl border border-white/10 bg-black/30 object-contain"
                            />
                          </div>
                        ) : null}

                        <div className="mt-2 flex items-center justify-between gap-2 text-[11px] text-[var(--text-secondary)]">
                          <span>{displayState.status}</span>
                          {displayAsset ? (
                            <a
                              href={displayAsset.outputPath}
                              target="_blank"
                              rel="noreferrer"
                              className="text-cyan-300 hover:text-cyan-200"
                            >
                              Open enhanced image
                            </a>
                          ) : null}
                        </div>

                        {displayState.error ? (
                          <div className="mt-3 rounded-xl border border-red-400/40 bg-red-500/10 p-3 text-xs text-red-200">
                            {displayState.error}
                          </div>
                        ) : null}
                      </div>

                      <div className="space-y-3 p-3 text-sm">
                        <div>
                          <div className="mb-1 text-[11px] uppercase tracking-wide text-[var(--text-secondary)]">
                            What It Is
                          </div>
                          <p className="text-white">{component.summary}</p>
                        </div>

                        <div>
                          <div className="mb-1 text-[11px] uppercase tracking-wide text-[var(--text-secondary)]">
                            How It Works
                          </div>
                          <p className="text-white">{component.functionDescription}</p>
                        </div>

                        <div className="flex flex-wrap gap-2 text-xs">
                          <StatusBadge label={`${component.evidence.length} evidence view${component.evidence.length === 1 ? "" : "s"}`} />
                          {component.canonicalRefNumber ? (
                            <StatusBadge label={`Ref ${component.canonicalRefNumber}`} tone="success" />
                          ) : null}
                          <StatusBadge label={component.buildableStatus ?? "buildable"} />
                          {component.refNumbers.map((refNumber) => (
                            <StatusBadge key={`${component.id}-${refNumber}`} label={`Ref ${refNumber}`} tone="success" />
                          ))}
                          <StatusBadge
                            label={`Scale ${(component.scaleHints?.relativeArea ?? 0) * 100 < 1 ? "<1" : Math.round((component.scaleHints?.relativeArea ?? 0) * 100)}%`}
                          />
                        </div>

                        <div className="grid grid-cols-3 gap-2">
                          {component.evidence.slice(0, 3).map((evidence, index) => (
                            <img
                              key={`${evidence.candidateId}-${evidence.figureId}-${evidence.pageNumber}-${index}`}
                              src={evidence.imagePath}
                              alt={`${component.canonicalName} evidence ${evidence.figureLabel}`}
                              className="h-24 w-full rounded-xl border border-white/10 bg-black/30 object-contain"
                            />
                          ))}
                        </div>
                      </div>
                    </div>
                  );
                })}
              </div>
            )}
          </Panel>

          <div className="grid gap-6 xl:grid-cols-[1.25fr_0.75fr]">
            <Panel className="p-4 md:p-6">
              <div className="mb-4 flex items-center gap-3">
                <FileImage className="size-5 text-cyan-300" />
                <div>
                  <h2 className="text-lg font-semibold text-white">Source Figures</h2>
                  <p className="text-sm text-[var(--text-secondary)]">
                    Raw figure evidence is preserved for debugging, provenance, and future assembly work.
                  </p>
                </div>
              </div>

              <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
                {sortedFigures.map((figure) => (
                  <div key={figure.id} className="overflow-hidden rounded-2xl border border-white/10 bg-white/[0.03]">
                    <a href={figure.imagePath} target="_blank" rel="noreferrer" className="block">
                      <img
                        src={figure.imagePath}
                        alt={`${figure.label} page ${figure.pageNumber}`}
                        className="h-40 w-full bg-black/30 object-contain"
                      />
                    </a>
                    <div className="space-y-2 p-3 text-sm">
                      <div className="flex items-center justify-between gap-2">
                        <div className="font-medium text-white">{figure.label}</div>
                        <StatusBadge label={`p${figure.pageNumber}`} />
                      </div>
                      <p className="text-[var(--text-secondary)]">{figure.description}</p>
                      <div className="flex flex-wrap gap-2 text-xs">
                        <StatusBadge label={figure.analysisSource} tone="success" />
                        <StatusBadge label={`${figure.componentDetections.length} detections`} />
                        {figure.cropRegion ? <StatusBadge label="cropped" tone="success" /> : null}
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </Panel>

            <Panel className="p-4 md:p-6">
              <div className="mb-4 flex items-center gap-3">
                <Layers3 className="size-5 text-cyan-300" />
                <div>
                  <h2 className="text-lg font-semibold text-white">Review Outcomes</h2>
                  <p className="text-sm text-[var(--text-secondary)]">
                    Track what was skipped or merged while keeping the source evidence intact.
                  </p>
                </div>
              </div>

              {secondaryComponents.length === 0 ? (
                <div className="rounded-xl border border-dashed border-white/10 bg-black/20 p-4 text-sm text-[var(--text-secondary)]">
                  No skipped or redundant components yet.
                </div>
              ) : (
                <div className="space-y-3">
                  {secondaryComponents.map((component) => (
                    <div key={component.id} className="rounded-xl border border-white/10 bg-white/[0.03] p-3">
                      <div className="flex items-center justify-between gap-2">
                        <div className="font-medium text-white">{component.canonicalName}</div>
                        <StatusBadge
                          label={component.reviewStatus}
                          tone={component.reviewStatus === "redundant" ? "warn" : "default"}
                        />
                      </div>
                      <p className="mt-1 text-sm text-[var(--text-secondary)]">{component.summary}</p>
                      {component.mergeTargetId ? (
                        <div className="mt-2 text-xs text-cyan-300">Merged into {component.mergeTargetId}</div>
                      ) : null}
                    </div>
                  ))}
                </div>
              )}
            </Panel>
          </div>
        </>
      ) : null}
    </main>
  );
}
